const appStoreRegions = {
    africa: [
        { code: 'ao', name: 'Angola', emoji: '🇦🇴' },
        { code: 'bf', name: 'Burkina Faso', emoji: '🇧🇫' },
        { code: 'bw', name: 'Botswana', emoji: '🇧🇼' },
        { code: 'cg', name: 'Republic of Congo', emoji: '🇨🇬' },
        { code: 'cv', name: 'Cape Verde', emoji: '🇨🇻' },
        { code: 'dz', name: 'Algeria', emoji: '🇩🇿' },
        { code: 'eg', name: 'Egypt', emoji: '🇪🇬' },
        { code: 'gh', name: 'Ghana', emoji: '🇬🇭' },
        { code: 'gm', name: 'Gambia', emoji: '🇬🇲' },
        { code: 'gw', name: 'Guinea-Bissau', emoji: '🇬🇼' },
        { code: 'ke', name: 'Kenya', emoji: '🇰🇪' },
        { code: 'lr', name: 'Liberia', emoji: '🇱🇷' },
        { code: 'mg', name: 'Madagascar', emoji: '🇲🇬' },
        { code: 'ml', name: 'Mali', emoji: '🇲🇱' },
        { code: 'mr', name: 'Mauritania', emoji: '🇲🇷' },
        { code: 'mu', name: 'Mauritius', emoji: '🇲🇺' },
        { code: 'mw', name: 'Malawi', emoji: '🇲🇼' },
        { code: 'mz', name: 'Mozambique', emoji: '🇲🇿' },
        { code: 'na', name: 'Namibia', emoji: '🇳🇦' },
        { code: 'ne', name: 'Niger', emoji: '🇳🇪' },
        { code: 'ng', name: 'Nigeria', emoji: '🇳🇬' },
        { code: 'sc', name: 'Seychelles', emoji: '🇸🇨' },
        { code: 'sl', name: 'Sierra Leone', emoji: '🇸🇱' },
        { code: 'sn', name: 'Senegal', emoji: '🇸🇳' },
        { code: 'st', name: 'Sao Tome and Principe', emoji: '🇸🇹' },
        { code: 'sz', name: 'Swaziland', emoji: '🇸🇿' },
        { code: 'td', name: 'Chad', emoji: '🇹🇩' },
        { code: 'tn', name: 'Tunisia', emoji: '🇹🇳' },
        { code: 'tz', name: 'Tanzania', emoji: '🇹🇿' },
        { code: 'ug', name: 'Uganda', emoji: '🇺🇬' }
    ],
    asia: [
        { code: 'ae', name: 'United Arab Emirates', emoji: '🇦🇪' },
        { code: 'am', name: 'Armenia', emoji: '🇦🇲' },
        { code: 'az', name: 'Azerbaijan', emoji: '🇦🇿' },
        { code: 'bh', name: 'Bahrain', emoji: '🇧🇭' },
        { code: 'bn', name: 'Brunei', emoji: '🇧🇳' },
        { code: 'cn', name: 'China', emoji: '🇨🇳' },
        { code: 'hk', name: 'Hong Kong', emoji: '🇭🇰' },
        { code: 'id', name: 'Indonesia', emoji: '🇮🇩' },
        { code: 'il', name: 'Israel', emoji: '🇮🇱' },
        { code: 'in', name: 'India', emoji: '🇮🇳' },
        { code: 'jo', name: 'Jordan', emoji: '🇯🇴' },
        { code: 'jp', name: 'Japan', emoji: '🇯🇵' },
        { code: 'kg', name: 'Kyrgyzstan', emoji: '🇰🇬' },
        { code: 'kh', name: 'Cambodia', emoji: '🇰🇭' },
        { code: 'kr', name: 'South Korea', emoji: '🇰🇷' },
        { code: 'kw', name: 'Kuwait', emoji: '🇰🇼' },
        { code: 'kz', name: 'Kazakhstan', emoji: '🇰🇿' },
        { code: 'la', name: 'Laos', emoji: '🇱🇦' },
        { code: 'lb', name: 'Lebanon', emoji: '🇱🇧' },
        { code: 'lk', name: 'Sri Lanka', emoji: '🇱🇰' },
        { code: 'mn', name: 'Mongolia', emoji: '🇲🇳' },
        { code: 'mo', name: 'Macau', emoji: '🇲🇴' },
        { code: 'my', name: 'Malaysia', emoji: '🇲🇾' },
        { code: 'np', name: 'Nepal', emoji: '🇳🇵' },
        { code: 'om', name: 'Oman', emoji: '🇴🇲' },
        { code: 'ph', name: 'Philippines', emoji: '🇵🇭' },
        { code: 'pk', name: 'Pakistan', emoji: '🇵🇰' },
        { code: 'qa', name: 'Qatar', emoji: '🇶🇦' },
        { code: 'sa', name: 'Saudi Arabia', emoji: '🇸🇦' },
        { code: 'sg', name: 'Singapore', emoji: '🇸🇬' },
        { code: 'th', name: 'Thailand', emoji: '🇹🇭' },
        { code: 'tj', name: 'Tajikistan', emoji: '🇹🇯' },
        { code: 'tm', name: 'Turkmenistan', emoji: '🇹🇲' },
        { code: 'tr', name: 'Turkey', emoji: '🇹🇷' },
        { code: 'tw', name: 'Taiwan', emoji: '🇹🇼' },
        { code: 'uz', name: 'Uzbekistan', emoji: '🇺🇿' }
    ],
    europe: [
        { code: 'al', name: 'Albania', emoji: '🇦🇱' },
        { code: 'at', name: 'Austria', emoji: '🇦🇹' },
        { code: 'be', name: 'Belgium', emoji: '🇧🇪' },
        { code: 'bg', name: 'Bulgaria', emoji: '🇧🇬' },
        { code: 'by', name: 'Belarus', emoji: '🇧🇾' },
        { code: 'ba', name: 'Bosnia and Herzegovina', emoji: '🇧🇦' },
        { code: 'ch', name: 'Switzerland', emoji: '🇨🇭' },
        { code: 'cy', name: 'Cyprus', emoji: '🇨🇾' },
        { code: 'cz', name: 'Czech Republic', emoji: '🇨🇿' },
        { code: 'de', name: 'Germany', emoji: '🇩🇪' },
        { code: 'dk', name: 'Denmark', emoji: '🇩🇰' },
        { code: 'ee', name: 'Estonia', emoji: '🇪🇪' },
        { code: 'es', name: 'Spain', emoji: '🇪🇸' },
        { code: 'fi', name: 'Finland', emoji: '🇫🇮' },
        { code: 'fr', name: 'France', emoji: '🇫🇷' },
        { code: 'gb', name: 'United Kingdom', emoji: '🇬🇧' },
        { code: 'gr', name: 'Greece', emoji: '🇬🇷' },
        { code: 'ge', name: 'Georgia', emoji: '🇬🇪' },
        { code: 'hr', name: 'Croatia', emoji: '🇭🇷' },
        { code: 'hu', name: 'Hungary', emoji: '🇭🇺' },
        { code: 'ie', name: 'Ireland', emoji: '🇮🇪' },
        { code: 'is', name: 'Iceland', emoji: '🇮🇸' },
        { code: 'it', name: 'Italy', emoji: '🇮🇹' },
        { code: 'lt', name: 'Lithuania', emoji: '🇱🇹' },
        { code: 'lu', name: 'Luxembourg', emoji: '🇱🇺' },
        { code: 'lv', name: 'Latvia', emoji: '🇱🇻' },
        { code: 'md', name: 'Moldova', emoji: '🇲🇩' },
        { code: 'mk', name: 'Macedonia', emoji: '🇲🇰' },
        { code: 'mt', name: 'Malta', emoji: '🇲🇹' },
        { code: 'nl', name: 'Netherlands', emoji: '🇳🇱' },
        { code: 'no', name: 'Norway', emoji: '🇳🇴' },
        { code: 'pl', name: 'Poland', emoji: '🇵🇱' },
        { code: 'pt', name: 'Portugal', emoji: '🇵🇹' },
        { code: 'ro', name: 'Romania', emoji: '🇷🇴' },
        { code: 'ru', name: 'Russia', emoji: '🇷🇺' },
        { code: 'rs', name: 'Serbia', emoji: '🇷🇸' },
        { code: 'se', name: 'Sweden', emoji: '🇸🇪' },
        { code: 'si', name: 'Slovenia', emoji: '🇸🇮' },
        { code: 'sk', name: 'Slovakia', emoji: '🇸🇰' },
        { code: 'ua', name: 'Ukraine', emoji: '🇺🇦' }
    ],
    northAmerica: [
        { code: 'ag', name: 'Antigua and Barbuda', emoji: '🇦🇬' },
        { code: 'bb', name: 'Barbados', emoji: '🇧🇧' },
        { code: 'bm', name: 'Bermuda', emoji: '🇧🇲' },
        { code: 'bs', name: 'Bahamas', emoji: '🇧🇸' },
        { code: 'bz', name: 'Belize', emoji: '🇧🇿' },
        { code: 'ca', name: 'Canada', emoji: '🇨🇦' },
        { code: 'cr', name: 'Costa Rica', emoji: '🇨🇷' },
        { code: 'dm', name: 'Dominica', emoji: '🇩🇲' },
        { code: 'do', name: 'Dominican Republic', emoji: '🇩🇴' },
        { code: 'gd', name: 'Grenada', emoji: '🇬🇩' },
        { code: 'gt', name: 'Guatemala', emoji: '🇬🇹' },
        { code: 'hn', name: 'Honduras', emoji: '🇭🇳' },
        { code: 'jm', name: 'Jamaica', emoji: '🇯🇲' },
        { code: 'kn', name: 'Saint Kitts and Nevis', emoji: '🇰🇳' },
        { code: 'ky', name: 'Cayman Islands', emoji: '🇰🇾' },
        { code: 'lc', name: 'Saint Lucia', emoji: '🇱🇨' },
        { code: 'ms', name: 'Montserrat', emoji: '🇲🇸' },
        { code: 'mx', name: 'Mexico', emoji: '🇲🇽' },
        { code: 'ni', name: 'Nicaragua', emoji: '🇳🇮' },
        { code: 'pa', name: 'Panama', emoji: '🇵🇦' },
        { code: 'sv', name: 'El Salvador', emoji: '🇸🇻' },
        { code: 'tc', name: 'Turks and Caicos Islands', emoji: '🇹🇨' },
        { code: 'tt', name: 'Trinidad and Tobago', emoji: '🇹🇹' },
        { code: 'us', name: 'United States', emoji: '🇺🇸' },
        { code: 'vc', name: 'Saint Vincent and The Grenadines', emoji: '🇻🇨' },
        { code: 'vg', name: 'British Virgin Islands', emoji: '🇻🇬' }
    ],
    oceania: [
        { code: 'au', name: 'Australia', emoji: '🇦🇺' },
        { code: 'fj', name: 'Fiji', emoji: '🇫🇯' },
        { code: 'fm', name: 'Micronesia', emoji: '🇫🇲' },
        { code: 'nz', name: 'New Zealand', emoji: '🇳🇿' },
        { code: 'pg', name: 'Papua New Guinea', emoji: '🇵🇬' },
        { code: 'pw', name: 'Palau', emoji: '🇵🇼' },
        { code: 'sb', name: 'Solomon Islands', emoji: '🇸🇧' }
    ],
    southAmerica: [
        { code: 'ai', name: 'Anguilla', emoji: '🇦🇮' },
        { code: 'ar', name: 'Argentina', emoji: '🇦🇷' },
        { code: 'bo', name: 'Bolivia', emoji: '🇧🇴' },
        { code: 'br', name: 'Brazil', emoji: '🇧🇷' },
        { code: 'cl', name: 'Chile', emoji: '🇨🇱' },
        { code: 'co', name: 'Colombia', emoji: '🇨🇴' },
        { code: 'ec', name: 'Ecuador', emoji: '🇪🇨' },
        { code: 'gy', name: 'Guyana', emoji: '🇬🇾' },
        { code: 'pe', name: 'Peru', emoji: '🇵🇪' },
        { code: 'py', name: 'Paraguay', emoji: '🇵🇾' },
        { code: 'sr', name: 'Suriname', emoji: '🇸🇷' },
        { code: 'uy', name: 'Uruguay', emoji: '🇺🇾' },
    ]
};

export default appStoreRegions;
